services:
  docs:
    image: online_store_backend_local_docs
    container_name: online_store_backend_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./online_store_backend:/app/online_store_backend:z
    ports:
      - '9000:9000'
    command: /start-docs
